### PR TITLE
Fix Dualis login

### LINKED ISSUE #134: Anmeldung bei Dualis schlägt seit einiger Zeit fehl
Meinen Vorlseungsplan kann ich auf dem einen Handy (Iphone 12) anschauen. Auf dem anderen (Iphone 14) nicht. Fehlermeldung: Keine Verbindung (bestehende Internet Verbindung). Auf beiden Handys kann ich mich nicht bei Dualis anmelden. Fehlermeldung: Anmeldung fehlgeschlagen.

### PR DESCRIPTION
**Pull request by MaarxS**
Fixes the Dualis Login.
The position of the link is no longer inside the meta tags. I've changed the approach so that the readRedirectUrl function returns the First link which contains the substring "Startseite".

fixes #134

### CODE REVIEW

**Comment by Bennik2000** [comment]
Hey, thank you for this fix. 

Did you test your changes? When I try to build the app it does not compile because you deleted the `getUrlFromHeader` function. Can you try to fix this and confirm that the dualis authentication works again?

**Comment by Bennik2000** [comment]
@MaarxS can you please confirm that it works from your side?

**Comment by MaarxS** [comment]
I fixed it by readding the `getUrlFromHeader` function. I didn't notice that the function was stilled used.

I've tested it and the app and the dualis login works on the android emulator and on my android phone. The Unit tests also passed (apart from one that already failed before my changes).

**Comment by mwoelke** [comment]
I can confirm that dualis is working for me again after applying the readRedirectUrl() function from this pull request.

Thank you very much @MaarxS ! I've been looking into this as well the past days but you've been faster :)

**Comment by tuke307** [comment]
Why is only the Android Version getting Updated? #136

**Pull request merged**
